### ISSUE TITLE
Serializing into WOFF2?

### ISSUE THREAD

**Issue by gendx** [yeslogic/allsorts#101]
It seems that the [`subset()`](https://docs.rs/allsorts/latest/allsorts/subset/fn.subset.html) function is hard-coded to output the result in OpenType format. I was wondering if you would consider adding a way to serialize into WOFF2 format as well? WOFF2 can be useful for web contexts, to embed the font into SVG files, etc.

**Comment by wezm** [comment]
While possible, I don't think this would be a high priority as it's fairly easy to convert a TTF to WOFF2 with something like `woff2_compress` from <https://github.com/google/woff2>. Also be aware of #27 in regards to subsetting.
