### ISSUE TITLE
Support shaping Persian (farsi)

### ISSUE THREAD

**Issue by SaeedZhiany** [yeslogic/allsorts#23]
I have seen `README.md` file and I know Arabic shaping is not supported yet. as you probably know Arabic and Persian **almost** have the same character set, Persian just has more four characters than Arabic. the characters are `گ, چ, پ, ژ`.

I just raised this issue to inform you about that. so if there is any plan for supporting Arabic shaping in the future, please also consider supporting Persian as well.

Thanks

**Comment by mikeday** [comment]
As I recall the Arabic, Persian/Farsi, and Urdu scripts share the same Unicode blocks and OpenType script categories, so one implementation should work for all three. The one requirement to keep in mind is passing in the correct language tag, as some fonts may offer different feature lookups for different languages.

**Comment by alfiedotwtf** [comment]
Tests for Farsi, Sindhi, and Urdu have now been added, and they'll be merged into Allsorts in the coming days.
