### ISSUE TITLE
Inconsistent statements about hebrew support

### ISSUE THREAD

**Issue by est31** [yeslogic/allsorts#28]
In the Readme, it both says that Hebrew shaping is supported and unsupported. Maybe you've added Hebrew support in the past and added it to the list of supported fonts, but forgot to remove it from the limitations?

**Comment by mikeday** [comment]
Oops! That should probably say Khmer is unsupported. :nerd_face:

**Comment by alfiedotwtf** [comment]
Thanks for that @est31. It's been updated, and will be merged in the coming days.

**Comment by est31** [comment]
For reference, the commit was 3fb6cb26a40ea555af4cfd7f96ee374c41b5bdbe

**Comment by est31** [comment]
Thanks for the fix! allsorts is a really great tool!
