### ISSUE TITLE
How to get the contours of a glyph?

### ISSUE THREAD

**Issue by fschutt** [yeslogic/allsorts#38]
I'm trying to extract the glyph as bezier curves / `LineTo`, `QuadraticCurveTo` / `CubicCurveTo` operations to render the glyph to an SVG file, is there a way to extract this information? Thanks.

**Comment by wezm** [comment]
We don't have anything that interprets the glyph outlines as drawing operations/normalises them to bezier/quadratic curves. However the raw glyph data is available through [GlyfTable](https://github.com/yeslogic/allsorts/blob/ad1208238c87cb158148dd8a15b1f03a54afd093/src/tables/glyf.rs#L78) and [CFF](https://github.com/yeslogic/allsorts/blob/ad1208238c87cb158148dd8a15b1f03a54afd093/src/cff.rs#L69). In case it's helpful as an example [GlyfTable::subset](https://github.com/yeslogic/allsorts/blob/ad1208238c87cb158148dd8a15b1f03a54afd093/src/tables/glyf.rs#L716-L733) includes code that loops over the glyphs. Similarly [CFF::subset](https://github.com/yeslogic/allsorts/blob/ad1208238c87cb158148dd8a15b1f03a54afd093/src/cff.rs#L536-L541) for CFF char strings.

Out of curiosity is this something that you were able to do in your previous implementation? If so, I'd be curious to look over the code as a reference. I also found [font_to_svg](https://github.com/donbright/font_to_svg) which translates font outlines to SVG, perhaps that's useful as a reference.

**Comment by fschutt** [comment]
I've used `owned_ttf_parser` and `rusttype` that both have functions to parse glyph outlines, but they only work for ttf fonts. I'm looking to replace my code here:

https://github.com/maps4print/azul/blob/97236351a46bc04e0d71d2829ab2586e4c771329/azulc/src/svg.rs#L819-L828

and here: 

https://github.com/maps4print/azul/blob/97236351a46bc04e0d71d2829ab2586e4c771329/azulc/src/svg.rs#L1280-L1317 

I want to migrate to allsorts so I can also add support for opentype and WOFF fonts. Since I need this anyway, I'll see if I can make a PR for adding a glyph outline parser. I've looked at the glyf table, doesn't seem that hard.

**Comment by fschutt** [comment]
Also the corresponding function in rusttype is here: https://docs.rs/rusttype/0.9.2/rusttype/struct.ScaledGlyph.html#method.build_outline

**Comment by wezm** [comment]
> I'll see if I can make a PR for adding a glyph outline parser. 

If you can hold off a little while I'll be working on something similar today. I'm going to work on a test harness that allows allsorts to be run against the [unicode text-rendering-tests](https://github.com/unicode-org/text-rendering-tests), and this will probably require doing this at the same time.

**Comment by fschutt** [comment]
Are you still working on this, otherwise I'd go ahead in the next few days to just implement a parser for the glyf table

**Comment by wezm** [comment]
I am, but I'm holidays until 6 Jan now.

**Comment by fschutt** [comment]
There is an implementation of a glyf parser in the rust-ttf-parser crate already and the crate author has given me permission to copy the glyf parser code. I have some time between the years, so I'll probably go ahead and just implement it, because I need it before I can release azul.

Enjoy your holiday!

**Comment by wezm** [comment]
Well this took longer to get into a release than expected but access to glyph contours is present in Allsorts 0.6: https://yeslogic.com/blog/allsorts-rust-font-shaping-engine-0-6/
