### ISSUE TITLE
Derive Copy + Clone for MaxpTable and CmapSubtable

### ISSUE THREAD

**Issue by fschutt** [yeslogic/allsorts#39]
Also it would be great if `lookup_glyph_index` was on the `owned::CmapSubtable` - together with conversion function to convert from a `CmapSubtable<'a>` to an `owned::CmapSubtable` and back - this way users can cache the `CmapSubtable` if needed.

I'm trying to create a struct that "owns" the cmap subtable, but if I create an `OwnedCmapSubtable` then looking up glyphs isn't available anymore

**Comment by fschutt** [comment]
See #40

**Comment by wezm** [comment]
Hmm right. The owned variant primarily exists to support writing fonts as part of subsetting. All of our glyph handling code goes via the [Font type](https://github.com/yeslogic/allsorts/blob/master/src/font.rs) — if you're not already using it I'd suggest taking a look as it's intended to be the primary shaping interface. It handles several caches but does not yet have a full glyph cache.
