### ISSUE TITLE
Make flate2/zlib feature optional to enable compiling to WASM.

### ISSUE THREAD

**Issue by ajrcarey** [yeslogic/allsorts#50]
Thank you for such a useful crate! As currently implemented, the use of the `flate2/zlib` feature in Cargo.toml prevents compiling to WASM, since zlib is not available. Would it be possible to make this dependency optional? Something like the following would do it:

```
[package]
name = "allsorts"
version = "0.6.0"
authors = ["YesLogic Pty. Ltd. <info@yeslogic.com>"]
edition = "2018"

homepage = "https://github.com/yeslogic/allsorts"
documentation = "https://docs.rs/crate/allsorts"
repository = "https://github.com/yeslogic/allsorts"

readme = "README.md"
license = "Apache-2.0"
include = ["/LICENSE", "src/**/*"]

description = "Font parser, shaping engine, and subsetter for OpenType, WOFF, and WOFF2"
keywords = ["font", "shaping", "opentype", "truetype", "parse"]
categories = ["text-processing"]

[dependencies]
bitflags = "1.0"
bitreader = "0.3.2"
brotli-decompressor = "2.3"
byteorder = "1.2"
encoding_rs = "0.8.16"
flate2 = { version = "1.0", default-features = false }
glyph-names = "0.1"
itertools = "0.8"
lazy_static = "1.3.0"
libc = "0.2"
log = "0.4"
num-traits = "0.2"
ouroboros = "0.9"
rustc-hash = "1.1.0"
tinyvec = { version = "1", features = ["alloc"] }
ucd-trie = "0.1.2"
unicode-canonical-combining-class = "0.1.0"
unicode-general-category = "0.3"
unicode-joining-type = "0.4.0"

# Optional dependencies
pathfinder_geometry = { version = "0.5.1", optional = true }

[dev-dependencies]
regex = "1.1.6"

# criterion = "0.3"

# [[bench]]
# name = "bench-shape"
# harness = false

# [[bench]]
# name = "bench-read"
# harness = false

[features]
default = ["outline", "zlib"]
prince = []
outline = ["pathfinder_geometry"]
zlib = ["flate2/zlib"]
miniz_oxide = ["flate2/default"]
```

The `flate2/zlib` feature is now exposed by `allsorts/zlib`, which is added to the default features. So by default everything remains exactly the same. But now consumers who want to compile to WASM (or other scenarios where zlib is not available) can remove that feature and use the `allsorts/miniz_oxide` feature instead.

No doubt there's other, possibly more elegant, ways of doing this, but this seems a simple enough solution.

Possibly related to #7.

**Comment by wezm** [comment]
That seems reasonable. Most of the YesLogic folks are on leave at the moment. We should be able to add this in the new year. I return 11 Jan, feel free to ping me at the end of that week if you haven't heard anything by then.

**Comment by wezm** [comment]
I've pushed a change to implement this. I hope to make a release this week but we've got a few other tweaks in the works that I'd like to include so will hold off for a day or so.

**Comment by ajrcarey** [comment]
Many thanks, I look forward to the next release.

**Comment by wezm** [comment]
New release has been published.
