### ISSUE TITLE
Variable fonts

### ISSUE THREAD

**Issue by LoganDark** [yeslogic/allsorts#51]
Is there any way to load a variable font and then get outlines at different weights? Will I have to parse tables and stuff manually like I have to do for outlines?

**Comment by wezm** [comment]
> Is there any way to load a variable font and then get outlines at different weights?

No, sorry we don't support variable fonts yet.

> Will I have to parse tables and stuff manually like I have to do for outlines?

Just in case you missed it, support for accessing outlines was added in the 0.6 release: https://yeslogic.com/blog/allsorts-rust-font-shaping-engine-0-6/#glyph-positioning-and-contours

**Comment by LoganDark** [comment]
> support for accessing outlines was added in the 0.6 release

by manually parsing tables. There's a LOT of work needed to get outlines.

**Comment by LoganDark** [comment]
I'd be willing to sponsor development of this feature in the coming months, if you're interested. I'm very interested in using allsorts for interactive user interfaces

**Comment by wezm** [comment]
Added in [0.15.0](https://github.com/yeslogic/allsorts/releases/tag/v0.15.0)
