### ISSUE TITLE
otf is not a valid font file

### ISSUE THREAD

**Issue by zhenzi0322** [yeslogic/allsorts#56]
ttf to otf conversion：
![image](https://user-images.githubusercontent.com/34839719/149919912-e4e6f2f0-206e-4c7c-bf76-a9bc1f846496.png)

**Comment by wezm** [comment]
Hi we will need more details to be able to help you. Please provide a sample of the code you've written to perform ttf to otf conversion with Allsorts.

**Comment by zhenzi0322** [comment]
> Hi we will need more details to be able to help you. Please provide a sample of the code you've written to perform ttf to otf conversion with Allsorts.

```rust
use std::borrow::Borrow;
use std::fs::File;
use std::io::Write;
use allsorts::binary::read::ReadScope;
use allsorts::font_data::FontData;
use allsorts::tables::{FontTableProvider, MaxpTable};
use allsorts::{subset, tag};

use std::error::Error;
type BoxError = Box<dyn Error>;

fn subset_all<F: FontTableProvider>(font_provider: &F, output_path: &str) -> Result<(), BoxError> {
    let table = font_provider.table_data(tag::MAXP)?.expect("no maxp table");
    let scope = ReadScope::new(table.borrow());
    let maxp = scope.read::<MaxpTable>()?;
    let glyph_ids = (0..maxp.num_glyphs).collect::<Vec<_>>();
    let new_font = subset::subset(font_provider, &glyph_ids, None)?;
    let mut output = File::create(output_path)?;
    output.write_all(&new_font)?;
    Ok(())
}

fn main() {
    let buffer = std::fs::read("static/ttf/1808.ttf")
    .expect("unable to read Klei.otf");
    let scope = ReadScope::new(&buffer);
    let font_file = scope.read::<FontData<'_>>().expect("unable to parse font");
    let provider = font_file
        .table_provider(4)
        .expect("unable to create table provider");
    let out_file = "static/demo1.otf";
    let is_ok = subset_all(&provider, out_file).is_ok();
    if is_ok {
        println!("Font conversion successful.{:?}", out_file);
    }
}
```

**Comment by wezm** [comment]
Thanks, that helps a lot. Unfortunately our subsetting functionality is not yet up to doing what you're trying to do. Issue #27 has some more information. From memory they main issue is that we aren't building a proper `cmap` table.

**Comment by zhenzi0322** [comment]
> Thanks, that helps a lot. Unfortunately our subsetting functionality is not yet up to doing what you're trying to do. Issue #27 has some more information. From memory the main issue is that we aren't building a proper `cmap` table.


Ok

**Comment by zhenzi0322** [comment]
> Thanks, that helps a lot. Unfortunately our subsetting functionality is not yet up to doing what you're trying to do. Issue #27 has some more information. From memory the main issue is that we aren't building a proper `cmap` table.

Will this feature be implemented in the future?

**Comment by wezm** [comment]
We would like to implement it but there's currently no firm plans/schedule for when it will be done.

**Comment by wezm** [comment]
I'm going to close this issue as we are tracking this in #27

**Comment by wezm** [comment]
Just letting you know that the 0.9 release (just published) should fix this issue.
