### ISSUE TITLE
Simple glyph flags capacity off by one?

### ISSUE THREAD

**Issue by wezm** [yeslogic/allsorts#66]
I think I might have the reserved capacity for simple glyph flags off by one (too small) here:

https://github.com/yeslogic/allsorts/blob/1685cc27919b303e47ef373125de8a1339f7d1ea/src/tables/glyf.rs#L391

**Comment by mikeday** [comment]
Why is it `number_of_contours` instead of `number_of_coordinates` since that's when the loop stops?

**Comment by wezm** [comment]
Right. I think it should be `number_of_coordinates`.
