### ISSUE TITLE
Does `allsorts` shape text in logical or visual order?

### ISSUE THREAD

**Issue by LoganDark** [yeslogic/allsorts#70]
So in [my prior discussion](https://github.com/yeslogic/allsorts/discussions/54) I asked for some more details on how to compose `allsorts` into a more complete layout engine. In there was some stuff like:

- Split text into runs of the same direction, script, font etc
- Shape each run individually then compose them later

My question is, does allsorts shape text in logical or visual order? If I'm shaping a run of Arabic text, do I need to have `unicode-bidi` reverse the codepoints before passing them to `Font::shape`, or is `TextDirection::RightToLeft` enough?

P.S. This is an issue because it should be documented

**Comment by wezm** [comment]
Had double check this but confirming that shaping is done in logical order so there is no need to reverse the input text when using `TextDirection::RightToLeft`.

> P.S. This is an issue because it should be documented

I'll keep it open until the docs have been updated.
