### ISSUE TITLE
Shaping is slow in Miri

### ISSUE THREAD

**Issue by LoganDark** [yeslogic/allsorts#74]
Shaping is slow in Miri.

Constructing a font is relatively fast, but shaping *anything*... well, I tried to shape the string `"a"` and it never finished.

I tried to use the OutlineBuilder however, and it immediately started emitting instructions to the OutlineSink.

So shaping specifically is doing something that Miri really does not like.

Also I found https://github.com/servo/pathfinder/issues/516 lol

**Comment by wezm** [comment]
Not really sure I can do much here as I'm not familiar with miri internals. It might be best raised as an issue on the miri repo with a minimum reproduction.

**Comment by LoganDark** [comment]
I think miri supports some sort of tracing or profiling; trying to find it. I'll let you know if there is something you can do.

**Comment by wezm** [comment]
Might close this since I think it's more a MIRI issue than an Allsorts issue.
