### ISSUE TITLE
Streamlined shaping API

### ISSUE THREAD

**Issue by tiffany352** [yeslogic/allsorts#8]
Harfbuzz has a simplified API where you create an `hb_buffer_t` and call `hb_shape()` on it, while with this crate it looks like you have to write a bunch of boilerplate to apply gsub, gpos, and cmap table transformations separately. Could that code be streamlined into an API oriented around converting characters -> glyph indices? With other inputs similar to Harfbuzz, such as the language to use for shaping localized forms, and any OpenType features to apply during shaping such as smallcaps.

I could also be misunderstanding. I'm going off of the example located here: https://github.com/yeslogic/allsorts-tools/blob/master/src/shape.rs

**Comment by mikeday** [comment]
Yes, the characters -> glyphs mapping is still being driven by Prince at the moment but we're definitely going to push that into Allsorts in the future.

**Comment by wezm** [comment]
Since Allsorts 0.5 there it's now easier to shape text. The `Font` type has a `shape` method that handles most shaping concerns. Note that [shape.rs in allsorts-tools](https://github.com/yeslogic/allsorts-tools/blob/5818fc99e57ae9f9392027888c73021cc46d1bb7/src/shape.rs) is now much simpler.
