### ISSUE TITLE
Possibly more modern library for accessing outlines?

### ISSUE THREAD

**Issue by stephanemagnenat** [yeslogic/allsorts#90]
Currently the outline module/option depends on `pathfinder_geometry`, which seems not very active nowadays. Is there a plan to abstract it (it seems it is not used a lot actually, so maybe even basic types/tuples could be used for the interface), or provide a more modern alternative, such as [kurbo](https://github.com/linebender/kurbo)?

**Comment by wezm** [comment]
Not sure there's a lot of benefit to changing since as you point out we're only using a small part of `pathfinding_geometry` and it's working well.

**Comment by stephanemagnenat** [comment]
I agree that `pathfinder_geometry` is not very heavy (both in terms of code and dependencies) so it probably doesn't matter too much. It's just that at the moment the Rust graphics ecosystem is quite fragmented and a realistic end-user project will likely have several different geometry libraries used at the same times. It is not a drama, but it might be helpful to try to reduce this duplication if possible. If you want to stick with `pathfindinder_geometry` I'm happy to close the issue.
