### ISSUE TITLE
xx.otf is not a valid font file after use subset

### ISSUE THREAD

**Issue by 821869798** [yeslogic/allsorts#92]
When I use the subset with Chinese characters attached, I cannot open the font file.
![image](https://github.com/yeslogic/allsorts/assets/12216185/11c34a62-c325-4389-8f1a-3ced2d1e9d00)

**Comment by wezm** [comment]
Yes some more work is needed to produce standalone fonts when subsetting. See https://github.com/yeslogic/allsorts/issues/27

**Comment by 821869798** [comment]
Thank you for your answer.
