### ISSUE TITLE
No way to extract number from Real

### ISSUE THREAD

**Issue by Victor-N-Suadicani** [yeslogic/allsorts#93]
The [`Real`](https://docs.rs/allsorts/latest/allsorts/cff/struct.Real.html) struct offers no way to extract the value of the number (for instance as an `f64`). The data is not even public so I can't even touch it and parse it myself.

The `ttf-parser` crates has [an implementation that parses the number](https://github.com/RazrFalcon/ttf-parser/blob/ba2d9c8b9a207951b7b07e9481bc74688762bd21/src/tables/cff/dict.rs#L188), perhaps something similar could be used.

**Comment by wezm** [comment]
I've pushed a fix for this and will aim to publish a release shortly. https://github.com/yeslogic/allsorts/commit/d5aea008814e05e7a70d15717dd0ae6f52034f11

**Comment by wezm** [comment]
Version 0.14.1 published.
